# Copyright 2024 DeepMind Technologies Limited
#
# AlphaFold 3 source code is licensed under CC BY-NC-SA 4.0. To view a copy of
# this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/
#
# To request access to the AlphaFold 3 model parameters, follow the process set
# out at https://github.com/google-deepmind/alphafold3. You may only use these
# if received directly from Google. Use is subject to terms of use available at
# https://github.com/google-deepmind/alphafold3/blob/main/WEIGHTS_TERMS_OF_USE.md

FROM docker.io/rocm/jax:rocm7.2.1-jax0.8.2-py3.12

# Some RUN statements are combined together to make Docker build run faster.
# Get latest package listing, install software-properties-common, git, wget,
# compilers and libraries.
# git is required for pyproject.toml toolchain's use of CMakeLists.txt.
# gcc, g++, make are required for compiling hmmer and AlphaFold 3 libaries.
# zlib is a required dependency of AlphaFold 3.
RUN apt-get update --quiet \
    && apt-get dist-upgrade --yes --quiet \
    && apt-get install --yes --quiet software-properties-common \
    && apt-get install --yes --quiet git wget gcc g++ gcc-10 g++-10 make zlib1g-dev zstd git python3.12-dev python3.12-venv

RUN python3.12 -m venv /alphafold3_venv
ENV PATH="/hmmer/bin:/alphafold3_venv/bin:$PATH"
# Update pip to the latest version. Not necessary in Docker, but good to do when
# this is used as a recipe for local installation since we rely on new pip
# features for secure installs.
RUN pip3 install --upgrade pip

# Install HMMER. Do so before copying the source code, so that docker can cache
# the image layer containing HMMER. Alternatively, you could also install it
# using `apt-get install hmmer` instead of bulding it from source, but we want
# to have control over the exact version of HMMER and also apply the sequence
# limit patch. Also note that eddylab.org unfortunately doesn't support HTTPS
# and the tar file published on GitHub is explicitly not recommended to be used
# for building from source.

# Download, check hash, and extract the HMMER source code.
RUN mkdir /hmmer_build /hmmer ; \
    wget http://eddylab.org/software/hmmer/hmmer-3.4.tar.gz --directory-prefix /hmmer_build ; \
    (cd /hmmer_build && echo "ca70d94fd0cf271bd7063423aabb116d42de533117343a9b27a65c17ff06fbf3 hmmer-3.4.tar.gz" | sha256sum --check) && \
    (cd /hmmer_build && tar zxf hmmer-3.4.tar.gz && rm hmmer-3.4.tar.gz)

# Apply the --seq_limit patch to HMMER.
COPY docker/jackhmmer_seq_limit.patch /hmmer_build/
RUN (cd /hmmer_build && patch -p0 < jackhmmer_seq_limit.patch)

# Build HMMER.
RUN (cd /hmmer_build/hmmer-3.4 && ./configure --prefix /hmmer) && \
    (cd /hmmer_build/hmmer-3.4 && make -j) && \
    (cd /hmmer_build/hmmer-3.4 && make install) && \
    (cd /hmmer_build/hmmer-3.4/easel && make install) && \
    rm -R /hmmer_build



# Install the ROCM versions of JAX into the venv
RUN wget https://repo.radeon.com/rocm/manylinux/rocm-rel-7.2.1/jaxlib-0.8.2%2Brocm7.2.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl
RUN wget https://repo.radeon.com/rocm/manylinux/rocm-rel-7.2.1/jax_rocm7_plugin-0.8.2%2Brocm7.2.1-cp312-cp312-manylinux_2_28_x86_64.whl
RUN wget https://repo.radeon.com/rocm/manylinux/rocm-rel-7.2.1/jax_rocm7_pjrt-0.8.2%2Brocm7.2.1-py3-none-manylinux_2_28_x86_64.whl
RUN pip3 install jax*.whl \
                 'jax==0.8.2' 

# Copy the AlphaFold 3 source code from Github to the container and
# set the working directory to there.
RUN mkdir -p /app
WORKDIR /app
RUN git clone https://github.com/google-deepmind/alphafold3 alphafold
WORKDIR /app/alphafold
RUN git checkout ebfe70a27a6a1ad18c77664191c5f7fa486ebee9
COPY requirements_082.txt /app/alphafold/requirements-proteinshake.txt  

# Fix for alphafold3 thinking compute capability is a float
RUN sed -i 's|gpu_devices\[_GPU_DEVICE.value\].compute_capability|9.42|'  /app/alphafold/run_alphafold.py

# Install the Python dependencies AlphaFold 3 needs.
RUN pip3 install -r requirements-proteinshake.txt  
#RUN pip3 install jax-triton==0.3.1 --no-deps
RUN pip3 install .

# Build chemical components database (this binary was installed by pip).
RUN build_data

RUN pip3 uninstall -y jax jaxlib jax-cuda12-pjrt jax-cuda12-plugin
RUN pip3 install /jax*.whl 'jax==0.8.2'

# To work around a known XLA issue causing the compilation time to greatly
# increase, the following environment variable setting XLA flags must be enabled
# when running AlphaFold 3. Note that if using CUDA capability 7 GPUs, it is
# necessary to set the following XLA_FLAGS value instead:
# ENV XLA_FLAGS="--xla_disable_hlo_passes=custom-kernel-fusion-rewriter"
# (no need to disable gemm in that case as it is not supported for such GPU).
ENV XLA_FLAGS="--xla_gpu_enable_triton_gemm=false --xla_disable_hlo_passes=custom-kernel-fusion-rewriter"
# Memory settings used for folding up to 5,120 tokens on A100 80 GB.
ENV XLA_PYTHON_CLIENT_PREALLOCATE=true
ENV XLA_CLIENT_MEM_FRACTION=0.95
# Fix for ld.lld error as per https://github.com/ROCm/ROCm/issues/5998#issuecomment-3991811182
ENV LLVM_PATH=/opt/rocm/llvm
RUN sed -i 's|return float(device.compute_capability) >= 8.0|return True|g' /alphafold3_venv/lib/python3.12/site-packages/tokamax/_src/gpu_utils.py
RUN sed -i "s|return float(getattr(device, 'compute_capability', None))|return True|g" /alphafold3_venv/lib/python3.12/site-packages/tokamax/_src/gpu_utils.py
RUN sed -i 's|compute_capability = getattr(device, "compute_capability", None)|compute_capability = 9.42|g' /alphafold3_venv/lib/python3.12/site-packages/tokamax/_src/precision.py
CMD ["python3", "run_alphafold.py"]
