# Copyright 2024 DeepMind Technologies Limited
#
# AlphaFold 3 source code is licensed under CC BY-NC-SA 4.0. To view a copy of
# this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/
#
# To request access to the AlphaFold 3 model parameters, follow the process set
# out at https://github.com/google-deepmind/alphafold3. You may only use these
# if received directly from Google. Use is subject to terms of use available at
# https://github.com/google-deepmind/alphafold3/blob/main/WEIGHTS_TERMS_OF_USE.md

FROM docker.io/rocm/jax:rocm6.3.4-jax0.4.31-py3.12

# Some RUN statements are combined together to make Docker build run faster.
# Get latest package listing, install software-properties-common, git, wget,
# compilers and libraries.
# git is required for pyproject.toml toolchain's use of CMakeLists.txt.
# gcc, g++, make are required for compiling hmmer and AlphaFold 3 libaries.
# zlib is a required dependency of AlphaFold 3.
RUN apt-get update --quiet \
    && apt-get dist-upgrade --yes --quiet \
    && apt-get install --yes --quiet software-properties-common \
    && apt-get install --yes --quiet git wget gcc g++ gcc-10 g++-10 make zlib1g-dev zstd hmmer

RUN python3.12 -m venv /alphafold3_venv
ENV PATH="/alphafold3_venv/bin:$PATH"
# Update pip to the latest version. Not necessary in Docker, but good to do when
# this is used as a recipe for local installation since we rely on new pip
# features for secure installs.
RUN pip3 install --upgrade pip

# Install the ROCM versions of JAX into the venv
RUN wget https://repo.radeon.com/rocm/manylinux/rocm-rel-6.3.2/jaxlib-0.4.31-cp312-cp312-manylinux_2_28_x86_64.whl
RUN wget https://repo.radeon.com/rocm/manylinux/rocm-rel-6.3.2/jax-0.4.31-py3-none-any.whl
RUN wget https://repo.radeon.com/rocm/manylinux/rocm-rel-6.3.2/jax_rocm60_pjrt-0.4.31-py3-none-manylinux_2_28_x86_64.whl
RUN wget https://repo.radeon.com/rocm/manylinux/rocm-rel-6.3.2/jax_rocm60_plugin-0.4.31-cp312-cp312-manylinux_2_28_x86_64.whl
RUN pip3 install jaxlib-0.4.31-cp312-cp312-manylinux_2_28_x86_64.whl \
                 jax-0.4.31-py3-none-any.whl \
                 jax_rocm60_pjrt-0.4.31-py3-none-manylinux_2_28_x86_64.whl \
                 jax_rocm60_plugin-0.4.31-cp312-cp312-manylinux_2_28_x86_64.whl

# Copy the AlphaFold 3 source code from the local machine to the container and
# set the working directory to there.
COPY . /app/alphafold
WORKDIR /app/alphafold

# Install the Python dependencies AlphaFold 3 needs.
RUN pip3 install -r dev-requirements-jax-0.4.31.txt
RUN CC=gcc-10 CXX=g++-10 pip3 install --no-deps .
# Build chemical components database (this binary was installed by pip).
RUN build_data

# To work around a known XLA issue causing the compilation time to greatly
# increase, the following environment variable setting XLA flags must be enabled
# when running AlphaFold 3. Note that if using CUDA capability 7 GPUs, it is
# necessary to set the following XLA_FLAGS value instead:
# ENV XLA_FLAGS="--xla_disable_hlo_passes=custom-kernel-fusion-rewriter"
# (no need to disable gemm in that case as it is not supported for such GPU).
ENV XLA_FLAGS="--xla_gpu_enable_triton_gemm=false"
# Memory settings used for folding up to 5,120 tokens on A100 80 GB.
ENV XLA_PYTHON_CLIENT_PREALLOCATE=true
ENV XLA_CLIENT_MEM_FRACTION=0.95

CMD ["python3", "run_alphafold.py"]