# Copyright 2024 DeepMind Technologies Limited
#
# AlphaFold 3 source code is licensed under CC BY-NC-SA 4.0. To view a copy of
# this license, visit https://creativecommons.org/licenses/by-nc-sa/4.0/
#
# To request access to the AlphaFold 3 model parameters, follow the process set
# out at https://github.com/google-deepmind/alphafold3. You may only use these
# if received directly from Google. Use is subject to terms of use available at
# https://github.com/google-deepmind/alphafold3/blob/main/WEIGHTS_TERMS_OF_USE.md

FROM docker.io/rocm/dev-ubuntu-24.04:7.1.1

# Some RUN statements are combined together to make Docker build run faster.
# Get latest package listing, install software-properties-common, git, wget,
# compilers and libraries.
# git is required for pyproject.toml toolchain's use of CMakeLists.txt.
# gcc, g++, make are required for compiling hmmer and AlphaFold 3 libaries.
# zlib is a required dependency of AlphaFold 3.
RUN apt-get update --quiet \
    && apt-get dist-upgrade --yes --quiet \
    && apt-get install --yes --quiet software-properties-common \
    && apt-get install --yes --quiet git wget gcc g++ gcc-10 g++-10 make zlib1g-dev zstd

RUN python3.12 -m venv /alphafold3_venv
ENV PATH="/hmmer/bin:/alphafold3_venv/bin:$PATH"

ENV AMDGPU_GFXMODEL=gfx942
ENV ROCM_VERSION=7.1.1
ENV ROCM_PATH=/opt/rocm-7.1.1
ENV ROCM_VERSION_BAZEL=7
ENV CLANG_COMPILER=/usr/bin/amdclang
ENV JAX_VERSION=7.1
ENV PATCHELF_VERSION=0.18.0
ENV JAX_PLATFORMS="rocm,cpu"

RUN apt-get install -q -y vim git sudo build-essential cmake libnuma1 wget gnupg2 m4 bash-completion git-core autoconf libtool autotools-dev \
      lsb-release libpapi-dev libpfm4-dev libudev1 rpm librpm-dev curl apt-utils vim tmux rsync \
      bison flex texinfo libnuma-dev pkg-config libibverbs-dev rdmacm-utils ssh locales gpg ca-certificates \
      gcc g++ gfortran ninja-build libtbb-dev nano python3-pip python3-dev python3-venv patchelf python3.12-venv python3.12-dev

# Update pip to the latest version. Not necessary in Docker, but good to do when
# this is used as a recipe for local installation since we rely on new pip
# features for secure installs.
RUN pip3 install --upgrade pip
RUN pip3 install 'cmake==3.28.3'

# Install HMMER. Do so before copying the source code, so that docker can cache
# the image layer containing HMMER. Alternatively, you could also install it
# using `apt-get install hmmer` instead of bulding it from source, but we want
# to have control over the exact version of HMMER and also apply the sequence
# limit patch. Also note that eddylab.org unfortunately doesn't support HTTPS
# and the tar file published on GitHub is explicitly not recommended to be used
# for building from source.

# Download, check hash, and extract the HMMER source code.
RUN mkdir /hmmer_build /hmmer ; \
    wget http://eddylab.org/software/hmmer/hmmer-3.4.tar.gz --directory-prefix /hmmer_build ; \
    (cd /hmmer_build && echo "ca70d94fd0cf271bd7063423aabb116d42de533117343a9b27a65c17ff06fbf3 hmmer-3.4.tar.gz" | sha256sum --check) && \
    (cd /hmmer_build && tar zxf hmmer-3.4.tar.gz && rm hmmer-3.4.tar.gz)

# Apply the --seq_limit patch to HMMER.
COPY docker/jackhmmer_seq_limit.patch /hmmer_build/
RUN (cd /hmmer_build && patch -p0 < jackhmmer_seq_limit.patch)

# Build HMMER.
RUN (cd /hmmer_build/hmmer-3.4 && CC=gcc-10 CXX=g++-10 ./configure --prefix /hmmer) ; \
    (cd /hmmer_build/hmmer-3.4 && CC=gcc-10 CXX=g++-10 make -j) ; \
    (cd /hmmer_build/hmmer-3.4 && CC=gcc-10 CXX=g++-10 make install) ; \
    (cd /hmmer_build/hmmer-3.4/easel && CC=gcc-10 CXX=g++-10  make install) ; \
    rm -R /hmmer_build



# Install the ROCM versions of JAX into the venv
RUN git clone --depth 1 --branch rocm-jaxlib-v0.7.1 https://github.com/ROCm/xla.git /xla
RUN git clone --depth 1 --branch rocm-jaxlib-v0.7.1 https://github.com/ROCm/jax.git /jax

ENV XLA_PATH=/xla

WORKDIR /jax

RUN sed -i "s|gfx900,gfx906,gfx908,gfx90a,gfx940,gfx941,gfx942,gfx1030,gfx1100,gfx1200,gfx1201|$AMDGPU_GFXMODEL|g" .bazelrc
RUN sed -i "s|/usr/lib/llvm-18/bin/clang|$CLANG_COMPILER|g" .bazelrc

RUN python3 build/build.py build --rocm_path=$ROCM_PATH \
                                         --bazel_options=--override_repository=xla=$XLA_PATH \
                                         --rocm_amdgpu_targets=$AMDGPU_GFXMODEL \
                                         --clang_path=$ROCM_PATH/lib/llvm/bin/clang \
                                         --rocm_version=$ROCM_VERSION_BAZEL \
                                         --use_clang=true \
                                         --wheels=jaxlib \
                                         --bazel_options=--jobs=128 \
                                         --bazel_startup_options=--host_jvm_args=-Xmx4g

RUN pip3 install opt_einsum setuptools --no-deps
RUN pip3 install dist/jax*.whl --force-reinstall
RUN pip3 install . --no-deps --no-build-isolation --force-reinstall

RUN git clone  --depth 1 --branch rocm-jax-v0.${JAX_VERSION} https://github.com/ROCm/rocm-jax.git /rocm-jax

WORKDIR /rocm-jax/jax_rocm_plugin

RUN sed -i "s|/usr/lib/llvm-18/bin/clang|$CLANG_COMPILER|g" .bazelrc 

RUN python3 build/build.py build --rocm_path=$ROCM_PATH \
                                         --bazel_options=--override_repository=xla=$XLA_PATH \
                                         --rocm_amdgpu_targets=$AMDGPU_GFXMODEL \
                                         --clang_path=$ROCM_PATH/lib/llvm/bin/clang \
                                         --rocm_version=$ROCM_VERSION_BAZEL \
                                         --use_clang=true \
                                         --wheels=jax-rocm-plugin,jax-rocm-pjrt \
                                         --bazel_options=--jobs=128 \
                                         --bazel_startup_options=--host_jvm_args=-Xmx4g

RUN pip3 install dist/jax*.whl --force-reinstall

RUN python3 -c 'import jax; print(jax.devices())'

# Copy the AlphaFold 3 source code from the local machine to the container and
# set the working directory to there.
COPY . /app/alphafold
WORKDIR /app/alphafold

# Install the Python dependencies AlphaFold 3 needs.
RUN pip3 install -r dev-requirements-jax-7.1.1.txt
#RUN pip3 install jax-triton==0.2.0 --no-deps
RUN CC=gcc-10 CXX=g++-10 pip3 install --no-deps .
# Build chemical components database (this binary was installed by pip).
RUN build_data

# To work around a known XLA issue causing the compilation time to greatly
# increase, the following environment variable setting XLA flags must be enabled
# when running AlphaFold 3. Note that if using CUDA capability 7 GPUs, it is
# necessary to set the following XLA_FLAGS value instead:
# ENV XLA_FLAGS="--xla_disable_hlo_passes=custom-kernel-fusion-rewriter"
# (no need to disable gemm in that case as it is not supported for such GPU).
ENV XLA_FLAGS="--xla_gpu_enable_triton_gemm=false"
# Memory settings used for folding up to 5,120 tokens on A100 80 GB.
ENV XLA_PYTHON_CLIENT_PREALLOCATE=true
ENV XLA_CLIENT_MEM_FRACTION=0.95

CMD ["python3", "run_alphafold.py"]
